### ISSUE TITLE
KnownChildSensitiveDataConsents data type

### ISSUE THREAD

**Issue by ym-corey** [InteractiveAdvertisingBureau/Global-Privacy-Platform#105]
In some `Us*Privacy` implementations `KnownChildSensitiveDataConsents` is an `int(2)` (e.g., [Utah](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-States/UT/GPP%20Extension%3A%20IAB%20Privacy%E2%80%99s%20Utah%20Privacy%20Technical%20Specification.md))and in others a `bitfield(2,3)` (e.g., [Connecticut](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-States/CT/GPP%20Extension%3A%20IAB%20Privacy%E2%80%99s%20Connecticut%20Privacy%20Technical%20Specification.md)).

I don't understand the reasoning for this but it seems like its usage is just `OPTED_OUT`, `NOT_OPTED_OUT`, `NOT_APPLICABLE`. Is this a mistake?

**Comment by omriariav** [comment]
We are facing the same issue, any update on this?

**Comment by lamrowena** [comment]
@ym-corey @omriariav whether it is an int vs bitfield depends on what the specific state regulations require in terms of consent. 

In the example listed, for Utah, you need consent to process sensitive data from a known child so the only thing that needs to be identified in this case is if this relates to known child, and if yes, was consent captured.  

In Connecticut, it's more specific than that. Not only do you need to indicate whether there was the appropriate consent to **process** sensitive data from a known child, you also separately need to indicate whether you received consent to **sell** their personal data, and whether you received consent to process the data specifically for **the purposes of targeted advertising**. So in this case, since there are multiple items, we make use of the bitfield data type.
