### ISSUE TITLE
String Format

### ISSUE THREAD

**Issue by Mokujinn** [InteractiveAdvertisingBureau/Global-Privacy-Platform#11]
TCF V2 has the consent string format laid out as bits for each field which I think is simpler to read than GPP with the just the field type. I think most folks parse as bits, so it’s easier to just see

TCF V2 format: "Version | Int | 32 bits | The version" 

GPP: "Version | Int (6) | The version"

Also, what does the (6) stand for?

**Comment by matita** [comment]
@Mokujinn it's an alias for `Int | 6 bits` as specified [in this section](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md#section-encoding).

**Comment by janwinkler** [comment]
all field types in gpp should have the exact same specific logic/meaning as in TCF. all field types that can have variable length, will give you the length in the spec (as you pointed out with your "int(6)" example). all fields with a fixed length (e.g. boolean, datetime, ...) dont require the additional information since its anyway fixed
