### ISSUE TITLE
Unclear in the specification: gdprApplies 

### ISSUE THREAD

**Issue by AramZS** [InteractiveAdvertisingBureau/Global-Privacy-Platform#16]
Extensive work and support has been hinged around `gdprApplies` for TCF. With the removal, between the last RFC and this specification, of the idea of API layering (the assumption that the main TCF or USP API is what is actually running underneath the GPP API) the shape of the objects that are returned from various API calls is now very unclear. 

`var s = __gpp('getSection',null, "tcfeuv2");` does this return the same exact object as TCFv2? Does it return some variation on [GPPData](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/CMP%20API%20Specification.md#gppdata-)? 

We should not expect, for example, API-accessing systems to decode the string to determine if they need to decode the string, as that has not been the expectation up to this point. If this is changing it needs to be significantly documented.

**Comment by janwinkler** [comment]
gdprApplies still exists since the TCF (EU) spec has not changed:
__gpp('tcfeuv2.getTCData', function (x,s){ console.log(x) }  )
equals
__tcfapi('getTCData', 2, function (x,s){ console.log(x) } )

The result of __gpp('getSection',null, "tcfeuv2"); is NOT the same as the TCF EU object (but very similar)
