### ISSUE TITLE
Macro expansion Spec not matching examples 

### ISSUE THREAD

**Issue by patmmccann** [InteractiveAdvertisingBureau/Global-Privacy-Platform#44]
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/606b99efc16b649c5c1f8f1d2eb0d0d3258c4a2d/Core/Consent%20String%20Specification.md?plain=1#L767 says the string should be base64 encoded, but the examples don't match. https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/606b99efc16b649c5c1f8f1d2eb0d0d3258c4a2d/Core/Consent%20String%20Specification.md?plain=1#L717

I think the example is correct on encoding?

Also, that same example has section 2 and 6 but sid is only 2?

**Comment by dtbarne** [comment]
I also found the reference to base64 encoding confusing in general, because it's not actually base64 encoding in the common sense, it's a custom mapping of characters to their alpha-index counterparts after looking through the [Java implementation](https://github.com/IABTechLab/iabgpp-java/blob/master/iabgpp-encoder/src/main/java/com/iab/gpp/encoder/datatype/encoder/Base64UrlEncoder.java).

eg. https://www.google.com/search?q=base64+decode

**Comment by taraschi-sp** [comment]
Just to second this, I'm also a bit confused here - the docs are inconsistent in the example strings they show.

The header example section - https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/606b99efc16b649c5c1f8f1d2eb0d0d3258c4a2d/Core/Consent%20String%20Specification.md?plain=1#L314

Does not match the gpp string example section - https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/606b99efc16b649c5c1f8f1d2eb0d0d3258c4a2d/Core/Consent%20String%20Specification.md?plain=1#L630

`DBACNY` vs `DBACNYA`

In the gpp string example isn't that extra `A` effectively padding? Should it be there or am I missing something?

**Comment by janwinkler** [comment]
@taraschi-sp Yes, there is a already a task to correct the examples and make it explicit how the encoding works.

as of the above: DBACNY is the correct one. the additional A would be padding and should not be there.

**Comment by lamrowena** [comment]
Related to #8, #6 so am closing this
