### ISSUE TITLE
Formatting of the getSection API command

### ISSUE THREAD

**Issue by yotam-g** [InteractiveAdvertisingBureau/Global-Privacy-Platform#47]
What is the format of the object returned for the getSection command? The GPP spec states "Section string parsed into an object according to the API specification" but the US-CA spec (as an example) doesn't contain any details on the object to be returned. More specifically, how are the sub sections meant to be represented in this object given that there are no field names specified for each sub section (core segment and gpc segment)? Thanks!

**Comment by janwinkler** [comment]
Two proposals:

a) If no subsection is mentioned:
__gpp('getSection', myFunction, "usca");
should give ONLY the first subsection (core section)
in order to access the second/third/fourth/... section, the parameter could changed:
__gpp('getSection', myFunction, "usca.0"); => output core section
__gpp('getSection', myFunction, "usca.1"); => output GPC Sub section
__gpp('getSection', myFunction, "usca.2"); => (doesnt exist for usca, would fail)
__gpp('getSection', myFunction, "usca.**SOMIDENTIFIER-TBD**"); => output Core AND GPC Sub section merged

b) Since we are anyway **breaking** things, the general output of the command could be changed
__gpp('getSection', myFunction, "usca"); --> output: [{...section 1...},{...section 2 ....}, ...]
Example: [{Version:1,SaleOptOutNotice: 0, SharingOptOutNotice: 1, ...}, {SubsectionType:1, Gpc:0} ]

**Comment by janwinkler** [comment]
Note: Group decision to go with version B.

Example for TCF Canada:

Call:
__gpp('getSection', myFunction, "tcfcav1"); //TO BE CHECKED: tcfca or tcfcav1?
Example output: 
[
 /* Core segment */
 {
  Version:1, 
  Created: Date (Thu Apr 13 2023 18:07:12 GMT+0200),
  LastUpdated: Date (Thu Apr 13 2023 18:07:12 GMT+0200),
  CmpId: 31, 
  CmpVersion: 123,
  ConsentScreen: 5,
  ...
  }, 
  /* Publisher Purposes Segment (optional) */
 {
  SegmentType:3, 
  PubPurposesExpressConsent : [1,2,3,4,5],
  PubPurposesImpliedConsent  : [6,7,8,9],
  ...
  } 
 ]
