### ISSUE TITLE
Minor: base64 for header 1 example is missing one character

### ISSUE THREAD

**Issue by guofangli** [InteractiveAdvertisingBureau/Global-Privacy-Platform#61]
It should be "**DBABMA**" instead of "**DBABM**".

**Comment by patmmccann** [comment]
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/d6563270d8ea2d3cb9f087f09d09442fb23efbf9/Core/Consent%20String%20Specification.md?plain=1#L272

**Comment by guofangli** [comment]
And in GPP String example, it's DBABMA.
 https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blame/main/Core/Consent%20String%20Specification.md#L603

**Comment by janwinkler** [comment]
the correct value is DBABM. the second example needs to be corrected. 
The issue with some examples is, that we used base64 instead of the "correct" base64-with-a-multiple-of-6 encoding. see issue here: https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/issues/6

@lamrowena Maybe a quick fix for 1.1?

**Comment by kgs** [comment]
@janwinkler why `DBABM` is correct one here? Many decoders fail on this one since it is incorrect base64url (for example: https://github.com/aklomp/base64). Why to invent something new here?

 According to base46 spec (including base64url) it is impossible to have `length(s) % 4 == 1` (1 or 2 are ok, padding applies here). See: https://datatracker.ietf.org/doc/html/rfc4648#section-4

**Comment by janwinkler** [comment]
@kgs we do not invent something new, but follow what is already happening with the TCF. in the TCF there was a guidance in TCF 1 that said it must be a multiple of 6. in tcf 2 this was removed and lead to issues now that TCF will be introducing new things like signatures/checksums. hence the decision was made to go with the shorter format and not the original base64urlsafe

**Comment by kgs** [comment]
@janwinkler so, in tcf 2 it is standard base64url?

**Comment by janwinkler** [comment]
no, it is this 6-bit encoding that looks like base64 but is not "real" base64

**Comment by kgs** [comment]
hmm, so what do you mean by sentence " in tcf 2 this was removed and lead to issues now that TCF will be introducing new things like signatures/checksums"?

**Comment by janwinkler** [comment]
@kgs In TCF 1 it specifically stated in the tech spec the encoding with 6 bits should be used, while TCF did not speficy ANY encoding. For TCF 2 there existed two official implementations - one with each of the encoding ways. In order to be clear for the future, the working group decided to take the 6-bit instead of the 24-bit encoding (the "fake" base64 over the real base64).

**Comment by kgs** [comment]
@janwinkler thanks for clarification, I think this should be explicitly stated in spec/readme that this is not normal base64 :)

**Comment by janwinkler** [comment]
@kgs I totally agree

**Comment by lamrowena** [comment]
Related to #8, #6 so am closing this
